### PR TITLE
update minimatch pkg

### PR DESCRIPTION
**Pull request by SherinV**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>

**Related Issue:**  stolostron/backlog#26439

### Description of changes

- Update package

### CODE REVIEW

**Comment by SherinV** [comment]
@zlayne Unit test doesn't work. Can you take a stab in updating minimatch? Not on this one. Maybe these versions don't work.

**Comment by jlpadilla** [comment]
@SherinV Some packages got updated to the next major version, which brings breaking changes (apollo, eslint, jest).

**Comment by SherinV** [comment]
```
➜  search-api git:(updMinimatchPkg) npm ls minimatch
@stolostron/search-api@2.5.0 /../search-api
├─┬ @babel/cli@7.19.3
│ └─┬ glob@7.2.3
│   └── minimatch@3.1.2  deduped
├─┬ eslint@7.32.0
│ ├─┬ @eslint/eslintrc@0.4.3
│ │ └── minimatch@3.1.2  deduped
│ ├─┬ @humanwhocodes/config-array@0.5.0
│ │ └── minimatch@3.1.2  deduped
│ └── minimatch@3.1.2
├─┬ eslint-plugin-import@2.26.0
│ └── minimatch@3.1.2  deduped
├─┬ jest@28.1.3
│ └─┬ @jest/core@28.1.3
│   └─┬ @jest/transform@28.1.3
│     └─┬ babel-plugin-istanbul@6.1.1
│       └─┬ test-exclude@6.0.0
│         └── minimatch@3.1.2  deduped
└─┬ nodemon@2.0.20
  └── minimatch@3.1.2  deduped
```

minimatch updated to 3.1.2

**Review by zlayne — APPROVED** [review]

**Pull request merged**
