### PR TITLE
[release-2.4] Fix sanitize input regex

### PR DESCRIPTION
**Pull request by SherinV**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>

**Related Issues:** 
- https://github.com/stolostron/backlog/issues/23796
- https://github.com/stolostron/backlog/issues/23851

### Description of changes

- Merges https://github.com/stolostron/search-api/pull/201 and https://github.com/stolostron/search-api/pull/198 into the release 2.4 branch.

### CODE REVIEW

**Review by xrajesh — APPROVED** [review]

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Comment by SherinV** [comment]
@jlpadilla I am not sure where these 2 jobs appear? Do we need those to merge?
ci/prow/lint and 
ci/prow/test-unit

**Comment by jlpadilla** [comment]
Oops, that's because of too much copy/paste in the prow config. 😞 
This PR should fix this repo. https://github.com/openshift/release/pull/32101

**Pull request merged**
