### PR TITLE
[release-2.4] Validate query inputs

### PR DESCRIPTION
**Pull request by jlpadilla**
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>

**Related Issue:**  https://github.com/stolostron/backlog/issues/23796

### Description of changes

- Merge #203 to release-2.4 branch
- Adds input validation.

PR for release-2.5 #205  should be merged first.

### CODE REVIEW

**Review by xrajesh — APPROVED** [review]

**Comment by xrajesh** [comment]
@atifshafi  QE Required for this.

**Review by SherinV — APPROVED** [review]

**Pull request merged**
