### PR TITLE
[release 2.6] update qs package

### PR DESCRIPTION
**Pull request by SherinV**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>

**Related Issue:** https://issues.redhat.com/browse/ACM-2281

### Description of changes

- Added...

### CODE REVIEW

**Comment by SherinV** [comment]
/hold
Will merge when 2.6 opens

**Review by Anxhela21 — APPROVED** [review]
/lgtm
/hold

**Review by Anxhela21 — APPROVED** [review]
/lgtm
/hold

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Pull request merged**
